<a href="https://colab.research.google.com/github/aheliroy-1121/machine_learning_assignment/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# assignment 1

import numpy as np

arr = np.arange(1, 11)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data type: int64
Sum: 55
Mean: 5.5
Maximum: 10
Minimum: 1


In [ ]:
# assignment 2

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix Addition:")
print(A + B)

print("\nMatrix Subtraction:")
print(A - B)

print("\nElement-wise Multiplication:")
print(A * B)

print("\nMatrix Multiplication:")
print(A @ B)

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
# assignment 3

import numpy as np

marks = np.array([
    [85, 90, 88, 92],
    [70, 65, 72, 68],
    [95, 91, 93, 96],
    [60, 75, 70, 80],
    [88, 84, 86, 90]
])
student_avg = np.mean(marks, axis=1)

subject_avg = np.mean(marks, axis=0)

highest = np.max(marks)

lowest = np.min(marks)

student_total = np.sum(marks, axis=1)

highest_student = np.argmax(student_total) + 1

print("Average marks of each student:")
print(student_avg)

print("\nAverage marks of each subject:")
print(subject_avg)

print("\nHighest marks:", highest)
print("Lowest marks:", lowest)

print("\nTotal marks of each student:")
print(student_total)

print("\nStudent with highest total marks: Student", highest_student)

Average marks of each student:
[88.75 68.75 93.75 71.25 87.  ]

Average marks of each subject:
[79.6 81.  81.8 85.2]

Highest marks: 96
Lowest marks: 60

Total marks of each student:
[355 275 375 285 348]

Student with highest total marks: Student 3


In [ ]:
# assignment 4

import numpy as np

image = np.array([
    [100, 120, 130],
    [150, 180, 200],
    [50, 80, 100]
])

normalized = image / 255

bright_image = image + 30

clipped_image = np.clip(bright_image, 0, 255)

average = np.mean(clipped_image)

print("Normalized Image:")
print(normalized)

print("\nImage after increasing brightness:")
print(bright_image)

print("\nImage after clipping:")
print(clipped_image)

print("\nAverage Pixel Intensity:", average)

Normalized Image:
[[0.39215686 0.47058824 0.50980392]
 [0.58823529 0.70588235 0.78431373]
 [0.19607843 0.31372549 0.39215686]]

Image after increasing brightness:
[[130 150 160]
 [180 210 230]
 [ 80 110 130]]

Image after clipping:
[[130 150 160]
 [180 210 230]
 [ 80 110 130]]

Average Pixel Intensity: 153.33333333333334


In [ ]:
# assignment 5

import numpy as np

sales = np.array([
    [120, 130, 140, 150, 160, 170],
    [100, 110, 120, 130, 140, 150],
    [150, 145, 160, 170, 180, 190],
    [90, 100, 110, 120, 130, 140]
])

total_sales = np.sum(sales, axis=1)

average_sales = np.mean(sales, axis=1)

best_product = np.argmax(total_sales) + 1

monthly_total = np.sum(sales, axis=0)

best_month = np.argmax(monthly_total) + 1

std_sales = np.std(sales, axis=1)

print("Total sales of each product:")
print(total_sales)

print("\nAverage monthly sales of each product:")
print(average_sales)

print("\nBest-selling product: Product", best_product)

print("\nTotal sales for each month:")
print(monthly_total)

print("\nMonth with highest overall sales: Month", best_month)

print("\nStandard deviation of each product:")
print(std_sales)

Total sales of each product:
[870 750 995 690]

Average monthly sales of each product:
[145.         125.         165.83333333 115.        ]

Best-selling product: Product 3

Total sales for each month:
[460 485 530 570 610 650]

Month with highest overall sales: Month 6

Standard deviation of each product:
[17.07825128 17.07825128 15.92081098 17.07825128]
