<a href="https://colab.research.google.com/github/aheliroy-1121/machine_learning_assignment/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

''' create a pandas series containing from 1 to 11 and also convet it into a dataframe  with a column
named numbers
**print**
series
dataframe
shape datatype
sum
mean
maximum minimum'''

In [ ]:
import pandas as pd

series = pd.Series([1,2,3,4,5,6,7,8,9,10])
df = pd.DataFrame({"NUMBERS: " : series})
print("series: ")
print(series)
print("\ndf: ")
print(df)
print("\n shape : " , df.shape)
print("\n datatype : " , df.dtypes)
print("\n sum : " , df.sum())
print("\n mean : " , df.mean())
print("\n max : " , df.max())
print("\n min : " , df.min())

series: 
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

df: 
   NUMBERS: 
0          1
1          2
2          3
3          4
4          5
5          6
6          7
7          8
8          9
9         10

 shape :  (10, 1)

 datatype :  NUMBERS:     int64
dtype: object

 sum :  NUMBERS:     55
dtype: int64

 mean :  NUMBERS:     5.5
dtype: float64

 max :  NUMBERS:     10
dtype: int64

 min :  NUMBERS:     1
dtype: int64


create two 3 x 3 using data below with colum labels["c1, c2, c3"] and row levels ["r1, r2, r3"]
1. data frame addition
2. df subtraction
3. element wise multiplication
4. matix multiplication using dot

In [ ]:
import pandas as pd

A = pd.DataFrame(
    [[1,2,3],
     [4,5,6],
     [6,7,8]],
     index = ["r1", "r2", "r3"],
     columns = ["c1", "c2", "c3"]
)

B = pd.DataFrame(
    [[9,8,7],
     [6,5,4],
     [3,2,1]],
     index = ["r1", "r2", "r3"],
     columns = ["c1", "c2", "c3"]

)
print("data frame A:", A)
print("data frame B:", B)
print("data frame addition: ")
print(A + B)
print("\ndata frame subtraction: ")
print(A - B)
print("\nelement wise multiplication: ")
print(A * B)
print("\nmatrix multiplication using dot: ")
print(A.values.dot(B.values))

data frame A:     c1  c2  c3
r1   1   2   3
r2   4   5   6
r3   6   7   8
data frame B:     c1  c2  c3
r1   9   8   7
r2   6   5   4
r3   3   2   1
data frame addition: 
    c1  c2  c3
r1  10  10  10
r2  10  10  10
r3   9   9   9

data frame subtraction: 
    c1  c2  c3
r1  -8  -6  -4
r2  -2   0   2
r3   3   5   7

element wise multiplication: 
    c1  c2  c3
r1   9  16  21
r2  24  25  24
r3  18  14   8

matrix multiplication using dot: 
[[ 30  24  18]
 [ 84  69  54]
 [120  99  78]]


Student Maths Science English History
Amit 85 90 88 92
Bhavna 70 65 72 68
Chirag 95 91 93 96
Divya 60 75 70 80
Esha 88 84 86 90
Find:
1. Average marks of each student
2. Average marks of each subject
3. Highest and lowest marks
4. Student having the highest total marks
5. Sort the DataFrame by total marks in descending order

In [ ]:
import pandas as pd

data = {
    "student": ["Amit", "Bhavna", "Chirag", "Divya", "Esha"],
    "maths": [85, 70, 65, 97, 9],
    "science": [90, 65, 91, 75, 87],
    "bliology": [88, 72, 93, 80, 84],
    "history": [92, 68, 96, 87, 54]
}

df = pd.DataFrame(data)
df.set_index("student", inplace=True)
print("student datA:")
print(df)

df["avg"] = df.mean(axis = 1)

print("aVERAGE MARKS OF EACH STUDENT: ")
print(df["avg"])

print("avg marks of each sublect: ")
print(df.mean())

print("highest and lowest marks: ")
print("highest: ")
print(df.max())
print("lowest: ")
print(df.min())

df["total"] = df[["maths", "science", "bliology", "history"]].sum(axis=1)
print("student having the highest total marks: ")
print(df[df["total"] == df["total"].max()])

print("sort the DataFrame by total marks in descending order: ")
print(df.sort_values(by="total", ascending=False))


student datA:
         maths  science  bliology  history
student                                   
Amit        85       90        88       92
Bhavna      70       65        72       68
Chirag      65       91        93       96
Divya       97       75        80       87
Esha         9       87        84       54
aVERAGE MARKS OF EACH STUDENT: 
student
Amit      88.75
Bhavna    68.75
Chirag    86.25
Divya     84.75
Esha      58.50
Name: avg, dtype: float64
avg marks of each sublect: 
maths       65.2
science     81.6
bliology    83.4
history     79.4
avg         77.4
dtype: float64
highest and lowest marks: 
highest: 
maths       97.00
science     91.00
bliology    93.00
history     96.00
avg         88.75
dtype: float64
lowest: 
maths        9.0
science     65.0
bliology    72.0
history     54.0
avg         58.5
dtype: float64
student having the highest total marks: 
         maths  science  bliology  history    avg  total
student                                                 
Amit 

4. A dataset recording the temperature (°C) of a city over 7 days has some missing readings, represented below as a
DataFrame.

Day Day1 Day2 Day3 Day4 Day5 Day6 Day7

Temperature 30 NaN 32 29 NaN 35 31
Perform:
1. Identify missing values using isnull()
2. Fill missing values with the mean temperature
3. Fill missing values using forward fill (ffill)
4. Drop rows/columns containing missing values
5. Calculate the average temperature after cleaning the data


In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Day": ["Day1", "Day2", "Day3", "Day4", "Day5", "Day6", "Day7"],
    "Temperature": [30, np.nan, 32, 29, np.nan, 35, 31]
})

print("og df: ")
print(df)

print("\nmissing values: ")
print(df.isnull())

print("\n missing values with the mean temperature: ")
mean_temp = df["Temperature"].mean()
df_mean_filled = df.copy()
df_mean_filled["Temperature"] = df_mean_filled["Temperature"].fillna(mean_temp)
print(df_mean_filled)

print("\nmissing values using forward fill (ffill): ")
df_ffill = df.copy()
df_ffill["Temperature"] = df_ffill["Temperature"].ffill()
print(df_ffill)

print("\ndrop rows/columns containing missing values: ")
df_dropna = df.copy()
print(df_dropna)

print("\n avg temp after cleaning the data (after dropna): ")
avg_temp_after_dropna = df_dropna["Temperature"].mean()
print(avg_temp_after_dropna)


og df: 
    Day  Temperature
0  Day1         30.0
1  Day2          NaN
2  Day3         32.0
3  Day4         29.0
4  Day5          NaN
5  Day6         35.0
6  Day7         31.0

missing values: 
     Day  Temperature
0  False        False
1  False         True
2  False        False
3  False        False
4  False         True
5  False        False
6  False        False

 missing values with the mean temperature: 
    Day  Temperature
0  Day1         30.0
1  Day2         31.4
2  Day3         32.0
3  Day4         29.0
4  Day5         31.4
5  Day6         35.0
6  Day7         31.0

missing values using forward fill (ffill): 
    Day  Temperature
0  Day1         30.0
1  Day2         30.0
2  Day3         32.0
3  Day4         29.0
4  Day5         29.0
5  Day6         35.0
6  Day7         31.0

drop rows/columns containing missing values: 
    Day  Temperature
0  Day1         30.0
2  Day3         32.0
3  Day4         29.0
5  Day6         35.0
6  Day7         31.0

 avg temp after cleaning the d

5. A company records the monthly sales of 4 products over 6 months in the DataFrame below.
Product Jan Feb Mar Apr May Jun
Product A 120 130 140 150 160 170
Product B 100 110 120 130 140 150
Product C 150 145 160 170 180 190
Product D 90 100 110 120 130 140
Perform the following:

a. Total sales of each product using groupby / sum()
b. Average monthly sales of each product
c. Best-selling product overall
d. Month with the highest overall sales
e. Standard deviation of sales for each product
e. Create a pivot table showing total sales per product per quarter (Q1: Jan–Mar, Q2: Apr–Jun)

In [ ]:
import pandas as pd

data = {
    "Product": ["A", "B", "C", "D"],
    "Jan": [120, 100, 150, 90],
    "Feb": [130, 110, 160, 90],
    "Mar": [140, 120, 170, 100],
    "Apr": [150, 130, 180, 120],
    "May": [160, 140, 190, 130],
    "Jun": [170, 150, 200, 150]
}
df = pd.DataFrame(data)
print("og df: ")
print(df)

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
df["Total"] = df[months].sum(axis=1)

print("\ntotal sales of each product: ")
print(df.groupby("Product")["Total"].sum())

print("\naverage monthly sales of each product: ")
print(df[months].mean())

print("\nbest-selling product overall: ")
print(df.loc[df["Total"].idxmax(), "Product"])

monthly_sales = df[months].values.flatten()
print("\nmonth with the highest overall sales: ")
print(pd.Series(monthly_sales).idxmax())

print("\nstandard deviation of sales for each product: ")
print(df[months].std())

df["q1"] = df[["Jan", "Feb", "Mar"]].sum(axis=1)
df["q2"] = df[["Apr", "May", "Jun"]].sum(axis=1)
pivot_table = pd.pivot_table(df, values=["q1", "q2"], index="Product")
print(pivot_table)

og df: 
  Product  Jan  Feb  Mar  Apr  May  Jun
0       A  120  130  140  150  160  170
1       B  100  110  120  130  140  150
2       C  150  160  170  180  190  200
3       D   90   90  100  120  130  150

total sales of each product: 
Product
A     870
B     750
C    1050
D     680
Name: Total, dtype: int64

average monthly sales of each product: 
Jan    115.0
Feb    122.5
Mar    132.5
Apr    145.0
May    155.0
Jun    167.5
dtype: float64

best-selling product overall: 
C

month with the highest overall sales: 
17

standard deviation of sales for each product: 
Jan    26.457513
Feb    29.860788
Mar    29.860788
Apr    26.457513
May    26.457513
Jun    23.629078
dtype: float64
            q1     q2
Product              
A        390.0  480.0
B        330.0  420.0
C        480.0  570.0
D        280.0  400.0
